"""
knowledge/tests.py

Tests for the Knowledge Base and Document API endpoints.

Coverage:
  - KnowledgeBase: create, list, retrieve, update, delete (ownership enforced)
  - Document: create with validation, ownership enforcement
  - Unauthenticated access → 401
  - Other user's resource → 404
"""

from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.test import APITestCase

from knowledge.models import Document, KnowledgeBase

User = get_user_model()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_user(email, password="StrongPass123!"):
    return User.objects.create_user(email=email, password=password)


def make_kb(owner, name="Test KB", description="Test knowledge base"):
    return KnowledgeBase.objects.create(
        owner=owner,
        name=name,
        description=description,
        chroma_collection_id=f"kb_test_{name.replace(' ', '_').lower()}_{owner.pk}",
    )


# ---------------------------------------------------------------------------
# KnowledgeBase CRUD
# ---------------------------------------------------------------------------

class KnowledgeBaseCreateTests(APITestCase):
    """POST /api/knowledge/bases/"""

    def setUp(self):
        self.user = make_user("alice@example.com")
        self.client.force_authenticate(user=self.user)
        self.url = "/api/knowledge/bases/"

    def test_create_kb_success(self):
        """Valid data creates a knowledge base and returns 201."""
        response = self.client.post(self.url, {
            "name": "Research Papers",
            "description": "ML papers collection",
        })
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data["name"], "Research Papers")
        # chroma_collection_id is auto-generated by the server
        self.assertTrue(response.data["chroma_collection_id"].startswith("kb_"))

    def test_create_kb_sets_owner_from_jwt(self):
        """Owner is always set from JWT — never from request body."""
        response = self.client.post(self.url, {"name": "My KB"})
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        kb = KnowledgeBase.objects.get(id=response.data["id"])
        self.assertEqual(kb.owner, self.user)

    def test_create_kb_unauthenticated(self):
        """Unauthenticated request returns 401."""
        self.client.force_authenticate(user=None)
        response = self.client.post(self.url, {"name": "Nope"})
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)


class KnowledgeBaseListTests(APITestCase):
    """GET /api/knowledge/bases/"""

    def setUp(self):
        self.alice = make_user("alice@example.com")
        self.bob = make_user("bob@example.com")
        make_kb(self.alice, "Alice KB")
        make_kb(self.bob, "Bob KB")
        self.client.force_authenticate(user=self.alice)

    def test_list_returns_only_own_kbs(self):
        """User only sees their own knowledge bases."""
        response = self.client.get("/api/knowledge/bases/")
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        names = [kb["name"] for kb in response.data["results"]]
        self.assertIn("Alice KB", names)
        self.assertNotIn("Bob KB", names)


class KnowledgeBaseRetrieveTests(APITestCase):
    """GET /api/knowledge/bases/{id}/"""

    def setUp(self):
        self.alice = make_user("alice@example.com")
        self.bob = make_user("bob@example.com")
        self.alice_kb = make_kb(self.alice, "Alice KB")
        self.bob_kb = make_kb(self.bob, "Bob KB")

    def test_retrieve_own_kb(self):
        """Owner can retrieve their knowledge base."""
        self.client.force_authenticate(user=self.alice)
        response = self.client.get(f"/api/knowledge/bases/{self.alice_kb.id}/")
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["name"], "Alice KB")

    def test_retrieve_other_users_kb_returns_404(self):
        """Accessing another user's KB returns 404 — not 403."""
        self.client.force_authenticate(user=self.alice)
        response = self.client.get(f"/api/knowledge/bases/{self.bob_kb.id}/")
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)


class KnowledgeBaseUpdateTests(APITestCase):
    """PATCH /api/knowledge/bases/{id}/"""

    def setUp(self):
        self.alice = make_user("alice@example.com")
        self.kb = make_kb(self.alice, "Original Name")
        self.client.force_authenticate(user=self.alice)

    def test_update_kb_name(self):
        """PATCH updates the name successfully."""
        response = self.client.patch(
            f"/api/knowledge/bases/{self.kb.id}/",
            {"name": "Updated Name"},
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["name"], "Updated Name")

    def test_cannot_update_other_users_kb(self):
        """Cannot PATCH another user's KB."""
        bob = make_user("bob@example.com")
        bob_kb = make_kb(bob, "Bob KB")
        response = self.client.patch(
            f"/api/knowledge/bases/{bob_kb.id}/",
            {"name": "Hacked"},
        )
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)


class KnowledgeBaseDeleteTests(APITestCase):
    """DELETE /api/knowledge/bases/{id}/"""

    def setUp(self):
        self.alice = make_user("alice@example.com")
        self.bob = make_user("bob@example.com")
        self.alice_kb = make_kb(self.alice, "Alice KB")
        self.bob_kb = make_kb(self.bob, "Bob KB")

    def test_delete_own_kb(self):
        """Owner can delete their KB."""
        self.client.force_authenticate(user=self.alice)
        response = self.client.delete(f"/api/knowledge/bases/{self.alice_kb.id}/")
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertFalse(KnowledgeBase.objects.filter(id=self.alice_kb.id).exists())

    def test_delete_other_users_kb_returns_404(self):
        """Cannot delete another user's KB."""
        self.client.force_authenticate(user=self.alice)
        response = self.client.delete(f"/api/knowledge/bases/{self.bob_kb.id}/")
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)


# ---------------------------------------------------------------------------
# Document validation
# ---------------------------------------------------------------------------

class DocumentValidationTests(APITestCase):
    """POST /api/knowledge/bases/{kb_id}/documents/"""

    def setUp(self):
        self.user = make_user("alice@example.com")
        self.kb = make_kb(self.user, "Test KB")
        self.client.force_authenticate(user=self.user)
        self.url = f"/api/knowledge/bases/{self.kb.id}/documents/"

    def test_website_requires_url(self):
        """Website source_type requires source_url."""
        response = self.client.post(self.url, {
            "title": "Web Page",
            "source_type": "website",
        })
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_pdf_requires_file(self):
        """PDF source_type requires a file upload."""
        response = self.client.post(self.url, {
            "title": "My PDF",
            "source_type": "pdf",
        })
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_cannot_access_other_users_kb_documents(self):
        """Listing documents under another user's KB returns 404."""
        bob = make_user("bob@example.com")
        bob_kb = make_kb(bob, "Bob KB")
        response = self.client.get(f"/api/knowledge/bases/{bob_kb.id}/documents/")
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_unauthenticated_access(self):
        """Unauthenticated request returns 401."""
        self.client.force_authenticate(user=None)
        response = self.client.get(self.url)
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
